apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-vcluster
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    #repoURL: https://myharbor.xyz/charts
    targetRevision: 0.12.1
    helm:
      values: |-
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            #- 192.168.0.184-192.168.0.184
            # change 2024.4.4 change range to vm master ip
            - 192.168.3.128-192.168.3.128
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
