apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-pipeline
  source:
    chart: vault
    #repoURL: https://helm.releases.hashicorp.com/
    repoURL: https://myharbor.xyz/charts
    targetRevision: 0.20.1
    helm:
      values: |-
        global:
          enabled: false
        injector:
          enabled: true
          authPath: auth/pipeline1
          externalVaultAddr: http://119.8.58.20:31820
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  ignoreDifferences:
  - group: "admissionregistration.k8s.io"
    kind: "MutatingWebhookConfiguration"
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
